name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: resulcankirti
          template: classic
          
          # İŞTE BURAYI TIRAŞLADIK: community ve metadata uçtu, sadece öz bilgiler kaldı!
          base: header, activity, repositories
          config_timezone: Europe/Istanbul

          # 1. Diller (En çok kullandığın teknolojiler)
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # 2. Kodlama Alışkanlıkları
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          # 3. 3D İzometrik Takvim
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
